/**
 * Regenerates the generated section of `public/_redirects`.
 *
 * Cloudflare Pages reads `_redirects` verbatim, so the file is checked in and
 * this script keeps the parts that are not hand-written in sync with their
 * sources:
 *
 *   - `src/data/docs-redirects.json` → one line per renamed docs page.
 *   - the sibling repos' `docs/` folders → one `.md` → route line per page, so
 *     the `foo.md` URLs already in Google's index land on the real page
 *     instead of 404ing (see `src/plugins/docs-md-links.ts` for the
 *     matching link rewrite).
 *
 * Only the `# BEGIN GENERATED` … `# END GENERATED` block is rewritten, so the
 * hand-maintained rules and their order — Pages takes the first match, so
 * specific rules must stay above the `/es/:id/docs/*` catch-all — are never
 * touched. The script is idempotent: running it twice produces the same bytes.
 *
 * Wired as `prebuild` because Astro copies `public/` into `dist/` *during* the
 * build; a postbuild step would land one directory too late.
 *
 * Runs on plain Node (24+) via native type-stripping. Run on demand:
 * `node scripts/build-redirects.ts`.
 */
import { existsSync, globSync, readFileSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { DOCS_BASES, DOCS_EXCLUDED_REDIRECTS, isDocsExcluded } from '../src/data/docs-bases.ts';

export { DOCS_BASES, DOCS_EXCLUDED_REDIRECTS, isDocsExcluded };

/** Repo root — npm scripts and jest both run from here (see build-md.ts). */
export const ROOT = process.cwd();
const REDIRECTS_PATH = resolve(ROOT, 'public/_redirects');
const DOCS_REDIRECTS_PATH = resolve(ROOT, 'src/data/docs-redirects.json');

export const BEGIN = '# BEGIN GENERATED by scripts/build-redirects.ts — do not edit';
export const END = '# END GENERATED by scripts/build-redirects.ts';

/**
 * The generated block's delimiters, matched by shape rather than by exact
 * text: a reworded comment must still *replace* the block, never append a
 * second one next to it. `[\s\S]*?` is non-greedy so an END always pairs with
 * the nearest following BEGIN.
 */
const BLOCK = /^# BEGIN GENERATED[^\n]*\n[\s\S]*?^# END GENERATED[^\n]*$/m;

/** Cloudflare Pages silently ignores a `_redirects` file past this length. */
const MAX_RULES = 2100;

/**
 * Hand-maintained rules, in priority order. Pages applies the first match, so
 * the specific removed routes come before the `/es/:id/docs/*` catch-all.
 * These are redirects for pages that no longer exist; the sources are
 * e40797b (experiments), f45c89e (cadforge), 20e5224 (demo-stage) and
 * 1d7eca2 (research).
 *
 * A fragment target (`/#experiments`) is fine: the browser resolves it against
 * the redirect response's own Location.
 */
export const STATIC_RULES: readonly string[] = [
  '/experiments/:id /:id/ 301',
  '/es/experiments/:id /es/:id/ 301',
  '/experiments /#experiments 301',
  '/es/experiments /es/#experiments 301',
  '/cadforge/* /cadspec/:splat 301',
  '/cadforge /cadspec/ 301',
  '/es/cadforge/* /es/cadspec/:splat 301',
  '/es/cadforge /es/cadspec/ 301',
  '/demo-stage /demostage/ 301',
  '/es/demo-stage /es/demostage/ 301',
  '/research /astro-denoise/ 301',
  '/es/research /es/astro-denoise/ 301',
  '/es/status /status/ 301',
  // Docs are English-only, so the Spanish spellings Google crawled are a
  // whole-segment mistake: send them to the English page rather than 404.
  '/es/:id/docs/* /:id/docs/:splat 301',
  '/es/:id/docs /:id/docs/ 301',
];

/**
 * The docs collections, mirroring `src/content.config.ts` — same ids, same
 * sibling bases. Both read `src/data/docs-bases.ts`, so they cannot drift.
 */
export type DocsRedirects = Record<string, Record<string, string>>;

/** Read the `{ experiment: { old_slug: new_slug } }` rename map. */
export function readDocsRedirects(path = DOCS_REDIRECTS_PATH): DocsRedirects {
  if (!existsSync(path)) return {};
  return JSON.parse(readFileSync(path, 'utf-8')) as DocsRedirects;
}

/** The site route a docs slug builds to; `index` is the collection root. */
export function docsRoute(id: string, slug: string): string {
  return `/${id}/docs/${slug === 'index' ? '' : `${slug}/`}`;
}

/** `canopy: { loops: graphs }` → `/canopy/docs/loops/ /canopy/docs/graphs/ 301`. */
export function docsRenameRules(redirects: DocsRedirects): string[] {
  const rules: string[] = [];
  for (const [id, slugs] of Object.entries(redirects)) {
    for (const [from, to] of Object.entries(slugs)) {
      rules.push(`${docsRoute(id, from)} ${docsRoute(id, to)} 301`);
    }
  }
  return rules;
}

/** Every published `.md` page of every collection, as `/<id>/docs/<slug>.md` sources. */
export function docsMdRules(bases: Record<string, string> = DOCS_BASES, root = ROOT): string[] {
  const rules: string[] = [];
  for (const [id, base] of Object.entries(bases)) {
    const basePath = resolve(root, base);
    if (!existsSync(basePath)) continue;
    for (const file of globSync('**/*.md', { cwd: basePath })) {
      if (isDocsExcluded(file)) continue;
      const slug = relative('.', file).replace(/\.md$/, '');
      rules.push(`/${id}/docs/${slug}.md ${docsRoute(id, slug)} 301`);
    }
  }
  return rules;
}

/** The generated block, sorted so a rebuild is byte-identical. */
export function generatedBlock(bases: Record<string, string> = DOCS_BASES, root = ROOT): string {
  const lines = [...docsRenameRules(readDocsRedirects()), ...docsMdRules(bases, root), ...DOCS_EXCLUDED_REDIRECTS].sort();
  return [BEGIN, ...lines, END].join('\n');
}

/** Replace the generated block in `current`, or append it if absent. */
export function spliceGeneratedBlock(current: string, block: string): string {
  const head = current.replace(/\r\n/g, '\n').replace(/\n*$/, '\n');
  const match = BLOCK.exec(head);
  if (!match) return `${head}\n${block}\n`;
  const before = head.slice(0, match.index);
  const after = head.slice(match.index + match[0].length).replace(/^\n+/, '');
  return `${before}${block}${after ? `\n${after}` : ''}\n`;
}

function main(): void {
  const current = existsSync(REDIRECTS_PATH) ? readFileSync(REDIRECTS_PATH, 'utf-8') : '';
  const next = spliceGeneratedBlock(current, generatedBlock());

  const ruleCount = next
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('#')).length;
  if (ruleCount > MAX_RULES) {
    throw new Error(`_redirects has ${ruleCount} rules, over Cloudflare Pages' ${MAX_RULES} limit`);
  }

  if (next === current) {
    console.log(`build-redirects: up to date (${ruleCount} rules).`);
    return;
  }
  writeFileSync(REDIRECTS_PATH, next, 'utf-8');
  console.log(`build-redirects: wrote ${REDIRECTS_PATH} (${ruleCount} rules).`);
}

const isDirectRun = process.argv[1] && /(?:^|[/\\])build-redirects\.(?:ts|js)$/.test(process.argv[1]);
if (isDirectRun) main();
