/**
 * Generates the machine-readable docs surfaces from the built site.
 *
 * `public/llms.txt` stays the hand-written source: this script splices a
 * `# BEGIN GENERATED … # END GENERATED` block into it (the same convention
 * `scripts/build-redirects.ts` uses for `public/_redirects`), so the head and
 * core pages stay hand-written and the file is idempotent. `dist/llms-full.txt`
 * concatenates every docs page's markdown twin in docs order.
 *
 * Generation reads `dist/` — the built truth the sitemap enumerates — so the
 * output cannot drift from the served pages. Wired as postbuild after
 * `build-md.ts` (twins must exist first) and before `check-seo.ts` (which
 * validates the result). Run on demand: `node scripts/build-llms.ts`.
 */
import { existsSync, globSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { NOINDEX } from './build-md.ts';
import { experiments } from '../src/lib/experiments.ts';

export { NOINDEX };

/** Repo root — npm scripts and jest both run from here (see build-md.ts). */
export const ROOT = process.cwd();
const TEMPLATE_PATH = resolve(ROOT, 'public/llms.txt');

/** llms-full.txt must stay under this; the build fails with the size if not. */
export const MAX_FULL_BYTES = 2 * 1024 * 1024;

export const BEGIN = '# BEGIN GENERATED by scripts/build-llms.ts — do not edit';
export const END = '# END GENERATED by scripts/build-llms.ts';

/**
 * The generated block's delimiters, matched by shape rather than by exact
 * text: a reworded comment must still *replace* the block, never append a
 * second one next to it.
 */
const BLOCK = /^# BEGIN GENERATED[^\n]*\n[\s\S]*?^# END GENERATED[^\n]*$/m;

export interface DocsPage {
  /** Leading-slash trailing-slash route, e.g. `/canopy/docs/installation/`. */
  slugPath: string;
  title: string;
  description: string;
  canonical: string;
  twinFile: string;
}

export interface DocsGroup {
  id: string;
  name: string;
  pages: DocsPage[];
}

/** Matches BaseLayout's `<meta name="description" …>` (double-quoted). */
const META_DESC = /<meta\s+name="description"\s+content="([^"]*)"/i;
/** Matches BaseLayout's `<link rel="canonical" href="…">`. */
const CANONICAL = /<link\s+rel="canonical"\s+href="([^"]+)"/i;

/**
 * Entities a built attribute or nav label can carry, back to the characters
 * they name. `&amp;` is replaced last so a literal `&amp;lt;` decodes to
 * `&lt;` and not to `<`.
 */
export function decodeEntities(s: string): string {
  return s
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#34;/gi, '"')
    .replace(/&apos;/gi, "'")
    .replace(/&#39;/gi, "'")
    .replace(/&#x27;/gi, "'")
    .replace(/&amp;/gi, '&');
}

/**
 * The docs-sidebar order: the `<aside>` of an experiment's docs index lists
 * every page in collection order (`[...slug].astro` sorts by `order`). The
 * aside's back link points at `/<id>/`, not `/<id>/docs/`, so the href filter
 * excludes it; only `class="item"` nav entries are kept.
 */
export function sidebarOrder(id: string, indexHtml: string): { slugPath: string; title: string }[] {
  const aside = indexHtml.match(/<aside[\s\S]*?<\/aside>/i)?.[0] ?? '';
  const out: { slugPath: string; title: string }[] = [];
  for (const m of aside.matchAll(/<a\b[^>]*>([\s\S]*?)<\/a>/gi)) {
    const tag = m[0];
    const href = /href="([^"]*)"/i.exec(tag)?.[1] ?? '';
    const cls = /class="([^"]*)"/i.exec(tag)?.[1] ?? '';
    if (!href.startsWith(`/${id}/docs/`)) continue;
    if (!cls.split(/\s+/).includes('item')) continue;
    const text = decodeEntities(m[1].replace(/<[^>]*>/g, '').replace(/\s+/g, ' ').trim());
    if (text) out.push({ slugPath: href, title: text });
  }
  return out;
}

/** A twin's first `# ` heading — the fallback title for a page missing from
 *  the sidebar (should never happen; the fallback keeps the build honest). */
export function twinTitle(twin: string): string {
  return twin.replace(/^---\n[\s\S]*?\n---\n/, '').match(/^# (.+)$/m)?.[1]?.trim() ?? '';
}

/**
 * Every docs page in docs order: registry order of experiments, sidebar order
 * within. Pages present in `dist/` but missing from the sidebar are appended
 * (sorted) so the count always matches the built tree — the guard against a
 * silently dropped page.
 */
export function docsPages(dist: string, exps = experiments): DocsGroup[] {
  const groups: DocsGroup[] = [];
  for (const exp of exps) {
    const indexFile = resolve(dist, exp.id, 'docs/index.html');
    if (!existsSync(indexFile)) continue;
    const ordered = sidebarOrder(exp.id, readFileSync(indexFile, 'utf-8'));
    const seen = new Set(ordered.map((p) => p.slugPath));
    const pages: DocsPage[] = [];
    const readPage = (slugPath: string, title: string): void => {
      const htmlFile = resolve(dist, `${slugPath.replace(/^\//, '')}index.html`);
      if (!existsSync(htmlFile)) {
        throw new Error(`build-llms: sidebar lists ${slugPath} but ${htmlFile} was not built`);
      }
      const html = readFileSync(htmlFile, 'utf-8');
      if (NOINDEX.test(html)) return;
      const description = decodeEntities(html.match(META_DESC)?.[1] ?? '');
      if (!description) throw new Error(`build-llms: ${slugPath} has no meta description`);
      const canonical = html.match(CANONICAL)?.[1] ?? '';
      if (canonical !== `https://univerlab.org${slugPath}`) {
        throw new Error(`build-llms: ${slugPath} canonical is ${JSON.stringify(canonical)}`);
      }
      const twinFile = resolve(dist, `${slugPath.replace(/^\//, '')}index.md`);
      if (!existsSync(twinFile)) {
        throw new Error(`build-llms: ${slugPath} has no markdown twin at ${twinFile}`);
      }
      pages.push({ slugPath, title, description, canonical, twinFile });
    };
    for (const { slugPath, title } of ordered) readPage(slugPath, title);
    // Anything the sidebar did not list still ships — appended, never dropped.
    const extra = globSync(`${exp.id}/docs/**/index.html`, { cwd: dist })
      .map((f) => `/${f.replace(/index\.html$/, '')}`)
      .filter((s) => !seen.has(s))
      .sort();
    for (const slugPath of extra) {
      const twinFile = resolve(dist, `${slugPath.replace(/^\//, '')}index.md`);
      const title = existsSync(twinFile) ? twinTitle(readFileSync(twinFile, 'utf-8')) : slugPath;
      if (!title) throw new Error(`build-llms: ${slugPath} has no title to list`);
      readPage(slugPath, title);
    }
    groups.push({ id: exp.id, name: exp.name, pages });
  }
  return groups;
}

/** Escape a title for use as markdown link text. */
export function escapeLinkText(s: string): string {
  return s.replace(/\s+/g, ' ').replace(/[\]()]/g, (c) => `\\${c}`);
}

/**
 * The generated `## Documentation` section: one line per docs page, grouped
 * by experiment — `- [<title>](<canonical>index.md): <meta description>`.
 */
export function docsBlock(groups: DocsGroup[]): string {
  const out = ['## Documentation', ''];
  for (const g of groups) {
    out.push(`### ${g.name}`, '');
    for (const p of g.pages) {
      out.push(`- [${escapeLinkText(p.title)}](${p.canonical}index.md): ${p.description}`);
    }
    out.push('');
  }
  return out.join('\n').replace(/\n+$/, '');
}

/** The full generated block, markers included. */
export function generatedBlock(groups: DocsGroup[]): string {
  return [BEGIN, docsBlock(groups), END].join('\n');
}

/** Replace the generated block in `current`, or append it if absent. */
export function spliceGeneratedBlock(current: string, block: string): string {
  const head = current.replace(/\r\n/g, '\n').replace(/\n*$/, '\n');
  const match = BLOCK.exec(head);
  if (!match) return `${head}\n${block}\n`;
  const before = head.slice(0, match.index);
  const after = head.slice(match.index + match[0].length).replace(/^\n+/, '');
  return `${before}${block}${after ? `\n${after}` : ''}\n`;
}

/** The hand-written part of the template: everything outside the markers. */
export function stripGeneratedBlock(template: string): string {
  return template.replace(/\r\n/g, '\n').replace(BLOCK, '').replace(/\n*$/, '\n');
}

/** A twin's body without its leading YAML front-matter (`title`/`source`
 *  live on as the `# <title>` + `Source:` lines the spec mandates). */
export function stripFrontMatter(twin: string): string {
  return twin.replace(/^---\n[\s\S]*?\n---\n/, '').replace(/^\n+/, '');
}

/**
 * The llms.txt head, then every docs page's markdown twin concatenated in
 * docs order, each preceded by `# <title>` and `Source: <canonical URL>`.
 * Throws naming the size when the result would exceed 2 MB.
 */
export function llmsFull(dist: string, template: string, groups?: DocsGroup[]): string {
  const docs = groups ?? docsPages(dist);
  const head = stripGeneratedBlock(template);
  const parts = [head];
  for (const g of docs) {
    for (const p of g.pages) {
      const body = stripFrontMatter(readFileSync(p.twinFile, 'utf-8')).replace(/\n*$/, '\n');
      parts.push(`\n# ${p.title}\nSource: ${p.canonical}\n\n${body}`);
    }
  }
  const text = parts.join('');
  const bytes = Buffer.byteLength(text, 'utf-8');
  if (bytes > MAX_FULL_BYTES) {
    throw new Error(
      `llms-full.txt is ${bytes} bytes (${(bytes / 1024 / 1024).toFixed(2)} MB), over the ${MAX_FULL_BYTES} byte limit`,
    );
  }
  return text;
}

function main(): void {
  const distDir = resolve(ROOT, 'dist');
  if (!existsSync(distDir)) {
    console.log('build-llms: dist/ not found, skipping.');
    return;
  }
  if (!existsSync(TEMPLATE_PATH)) {
    throw new Error(`build-llms: template ${TEMPLATE_PATH} not found`);
  }
  const template = readFileSync(TEMPLATE_PATH, 'utf-8');
  const docs = docsPages(distDir);
  const count = docs.reduce((n, g) => n + g.pages.length, 0);

  // public/ is copied into dist/ *during* the Astro build, so the generator
  // must write dist/llms.txt itself — the copy in dist/ is this build's stale
  // hand-written version.
  const next = spliceGeneratedBlock(template, generatedBlock(docs));
  if (next !== template) writeFileSync(TEMPLATE_PATH, next, 'utf-8');
  writeFileSync(resolve(distDir, 'llms.txt'), next, 'utf-8');

  const full = llmsFull(distDir, template, docs);
  writeFileSync(resolve(distDir, 'llms-full.txt'), full, 'utf-8');
  console.log(
    `build-llms: ${count} docs pages in ${docs.length} groups, llms-full.txt is ${Buffer.byteLength(full, 'utf-8')} bytes.`,
  );
}

const isDirectRun = process.argv[1] && /(?:^|[/\\])build-llms\.(?:ts|js)$/.test(process.argv[1]);
if (isDirectRun) main();
